// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {specter} from '../models';
import {client} from '../models';

export function AddForwarder(arg1:specter.Listener):Promise<void>;

export function AllForwardersStarted():Promise<boolean>;

export function Connected():Promise<boolean>;

export function ForwarderStarted(arg1:string):Promise<boolean>;

export function GetConnectedForwarderNodes():Promise<Array<specter.ForwarderNode>>;

export function GetConnectedTunnelNodes():Promise<Array<specter.TunnelNode>>;

export function GetPhantomConfig():Promise<specter.PhantomConfig>;

export function GetRegisteredHostnames():Promise<Array<string>>;

export function GetSpecterConfig():Promise<client.Config>;

export function RebuildTunnels(arg1:Array<client.Tunnel>):Promise<void>;

export function ReleaseTunnel(arg1:number):Promise<void>;

export function RemoveForwarder(arg1:number):Promise<void>;

export function StartAllForwarders():Promise<void>;

export function StartClient():Promise<void>;

export function StartForwarder(arg1:number):Promise<void>;

export function StopAllForwarders():Promise<void>;

export function StopClient():Promise<void>;

export function StopForwarder(arg1:number):Promise<void>;

export function Synchronize():Promise<void>;

export function UnpublishTunnel(arg1:number):Promise<void>;

export function UpdateApex(arg1:string):Promise<void>;

export function UpdateForwaderLabel(arg1:number,arg2:string):Promise<void>;

export function UpdatePhantomConfig(arg1:specter.PhantomConfig):Promise<void>;
