// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {specter} from '../models';
import {client} from '../models';

export function Connected():Promise<boolean>;

export function GetConnectedNodes():Promise<Array<specter.Node>>;

export function GetCurrentConfig():Promise<client.Config>;

export function GetPhantomConfig():Promise<specter.PhantomConfig>;

export function RebuildTunnels(arg1:Array<client.Tunnel>):Promise<void>;

export function StartClient():Promise<void>;

export function StopClient():Promise<void>;

export function Synchronize():Promise<void>;

export function UpdateApex(arg1:string):Promise<void>;

export function UpdatePhantomConfig(arg1:specter.PhantomConfig):Promise<void>;
