// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connected() {
  return window['go']['specter']['Application']['Connected']();
}

export function GetConnectedNodes() {
  return window['go']['specter']['Application']['GetConnectedNodes']();
}

export function GetCurrentConfig() {
  return window['go']['specter']['Application']['GetCurrentConfig']();
}

export function GetPhantomConfig() {
  return window['go']['specter']['Application']['GetPhantomConfig']();
}

export function RebuildTunnels(arg1) {
  return window['go']['specter']['Application']['RebuildTunnels'](arg1);
}

export function StartClient() {
  return window['go']['specter']['Application']['StartClient']();
}

export function StopClient() {
  return window['go']['specter']['Application']['StopClient']();
}

export function Synchronize() {
  return window['go']['specter']['Application']['Synchronize']();
}

export function UnpublishTunnel(arg1) {
  return window['go']['specter']['Application']['UnpublishTunnel'](arg1);
}

export function UpdateApex(arg1) {
  return window['go']['specter']['Application']['UpdateApex'](arg1);
}

export function UpdatePhantomConfig(arg1) {
  return window['go']['specter']['Application']['UpdatePhantomConfig'](arg1);
}
