// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddForwarder(arg1) {
  return window['go']['specter']['Application']['AddForwarder'](arg1);
}

export function AllForwardersStarted() {
  return window['go']['specter']['Application']['AllForwardersStarted']();
}

export function Connected() {
  return window['go']['specter']['Application']['Connected']();
}

export function ForwarderStarted(arg1) {
  return window['go']['specter']['Application']['ForwarderStarted'](arg1);
}

export function GetConnectedForwarderNodes() {
  return window['go']['specter']['Application']['GetConnectedForwarderNodes']();
}

export function GetConnectedTunnelNodes() {
  return window['go']['specter']['Application']['GetConnectedTunnelNodes']();
}

export function GetPhantomConfig() {
  return window['go']['specter']['Application']['GetPhantomConfig']();
}

export function GetRegisteredHostnames() {
  return window['go']['specter']['Application']['GetRegisteredHostnames']();
}

export function GetSpecterConfig() {
  return window['go']['specter']['Application']['GetSpecterConfig']();
}

export function RebuildTunnels(arg1) {
  return window['go']['specter']['Application']['RebuildTunnels'](arg1);
}

export function ReleaseTunnel(arg1) {
  return window['go']['specter']['Application']['ReleaseTunnel'](arg1);
}

export function RemoveForwarder(arg1) {
  return window['go']['specter']['Application']['RemoveForwarder'](arg1);
}

export function StartAllForwarders() {
  return window['go']['specter']['Application']['StartAllForwarders']();
}

export function StartClient() {
  return window['go']['specter']['Application']['StartClient']();
}

export function StartForwarder(arg1) {
  return window['go']['specter']['Application']['StartForwarder'](arg1);
}

export function StopAllForwarders() {
  return window['go']['specter']['Application']['StopAllForwarders']();
}

export function StopClient() {
  return window['go']['specter']['Application']['StopClient']();
}

export function StopForwarder(arg1) {
  return window['go']['specter']['Application']['StopForwarder'](arg1);
}

export function Synchronize() {
  return window['go']['specter']['Application']['Synchronize']();
}

export function UnpublishTunnel(arg1) {
  return window['go']['specter']['Application']['UnpublishTunnel'](arg1);
}

export function UpdateApex(arg1) {
  return window['go']['specter']['Application']['UpdateApex'](arg1);
}

export function UpdateForwaderLabel(arg1, arg2) {
  return window['go']['specter']['Application']['UpdateForwaderLabel'](arg1, arg2);
}

export function UpdatePhantomConfig(arg1) {
  return window['go']['specter']['Application']['UpdatePhantomConfig'](arg1);
}
