// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePaths() {
  return window['go']['specter']['Helper']['GetFilePaths']();
}

export function ParseTarget(arg1) {
  return window['go']['specter']['Helper']['ParseTarget'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['specter']['Helper']['SetClipboardText'](arg1);
}
