// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {specter} from '../models';

export function GetFilePaths():Promise<specter.Paths>;

export function ParseTarget(arg1:string):Promise<specter.Target>;

export function SetClipboardText(arg1:string):Promise<boolean>;

export function ValidateTarget(arg1:string):Promise<void>;
