// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {specter} from '../models';

export function ParseTarget(arg1:string):Promise<specter.Target>;
