FROM rust:1.67.1-alpine3.17 as builder

RUN apk update && apk add \
        make \
        gcc \
        g++ \
        zlib \
        zlib-dev

RUN cargo install --target x86_64-unknown-linux-musl apple-codesign

FROM alpine:3.17 AS runtime

COPY --from=builder /usr/local/cargo/bin/rcodesign /usr/local/bin

ENTRYPOINT ["/usr/local/bin/rcodesign"]
