// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {phantom} from '../models';

export function GetFilePaths():Promise<phantom.Paths>;

export function ParseTarget(arg1:string):Promise<phantom.Target>;

export function SetClipboardText(arg1:string):Promise<boolean>;

export function ValidateTarget(arg1:string):Promise<void>;
